Fix the device.c and fb.c for the kernel version 5.8
jserv/vcam pull request #4
Opened 2021-05-16 03:54 UTC by WayneLin1992

Problem: Some error infos are from the gcc
Cause: The kernel is from 4.15 to 5.8, Some API was changed or missed.
Solution: Check the git from kernel, and refer vivid which is device driver in kernel.

2021-05-16 08:46 UTC, jserv requested changes
Revise the subject of pull request and/or git commits. You can say, "adapt newer kernel APIs." In addition, we have to ensure the support from kernel v4.15 (shipped with Ubuntu Linux 18.04), v5.4 (shipped with Ubuntu Linux 20.04), to recent versions (such as v5.8+).

2021-05-16 23:40 UTC, jserv commented on Makefile
> +ifeq (${KERNEL_GT_5_4},1)
Don't do that. Change the C source files instead.

2021-05-16 23:41 UTC, jserv commented on Makefile
> +KERNEL_GT_5_4 = $(shell expr `uname -r` \> "5.4.0-0-generic")
The build system should be consistent among different kernel versions.

2021-05-16 23:42 UTC, jserv commented on Makefile
> +all: kmod vcam-util
Don't do that. If the kernel module fails to be built, it would altert.

2021-05-17 04:32 UTC, jserv commented
Use `git rebase -i` to squash the commits.

2021-05-17 23:03 UTC, jserv commented
After performing `git rebase`, do `git push --force`.

2021-05-17 23:05 UTC, jserv commented
> Problem: Some error infos are from the gcc
> Cause: The kernel is from 4.15 to 5.8, Some API was changed or missed.
> Solution: Check the git from kernel, and refer vivid which is device driver in kernel.

Improve the above descriptions by editing.

2021-05-18 04:44 UTC, jserv requested changes
The current git commit messages look a bit redundant. You can concentrate on the verified kernel versions AND known issues if any.

2021-05-18 14:05 UTC, WayneLin1992 commented
I already compile on the ubuntu 21.04 which is on linux v5.11. vcam is working.

2021-05-18 15:38 UTC, merged

2021-05-18 15:39 UTC, jserv commented
Thank @WayneLin1992 for contributing!